[package]
name = "frontend"
version = "0.1.0"
edition = "2018"

[dependencies]
seed = "0.9.2"
futures = "0.3"
async-trait = "0.1.73"
debug-cell = "0.1.1"

[dev-dependencies]
syntect = "5.1.0"

[dependencies.common]
path = "../common"
